name: CD-QA

on:
  push:
    branches: [develop]

env:
    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app to staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to fly
        uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy -c fly-qa.toml"
